version: '3.9'

services:
  redis:
    image: "redis:6.2.6"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  db:
    image: postgres:13.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp_development
    volumes:
      - "db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  rails:
    build: .
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    environment:
      - REDIS_URL_SIDEKIQ=redis://redis:6379/1
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

volumes:
  redis-data:
  db-data:
